version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/meme-api
  mongo:
    image: mongo
    ports:
      - "27017:27017"
